# Site settings
title: Vivaswat Shastry
#header-img: img/cap1.jpg
email: vivaswat@uchicago.edu
description: "Academic site for Vivaswat Shastry"
baseurl: ""
url: "http://vivaswats.github.io"
twitter_username: VivaswatShastry
github_username:  VivaswatS

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 4
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate, jekyll-feed]
